import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { TemplateSiteEntity } from '../../../../template-sites/infrastructure/persistence/relational/entities/template-sites.entity';
import {
  LightType,
  SoilType,
  Sunlight,
} from '../../../../template-sites/template-sites.enum';

@Injectable()
export class TemplateSiteSeedService {
  constructor(
    @InjectRepository(TemplateSiteEntity)
    private repository: Repository<TemplateSiteEntity>,
  ) {}

  async run() {
    const defaultSites: Partial<TemplateSiteEntity>[] = [
      {
        name: 'Ban công hướng Nam',
        description: 'Khu vực nhiều nắng buổi sáng',
        sunlight: Sunlight.FULL_SUN,
        lightDuration: 6,
        lightType: LightType.NATURAL,
        soilMoisture: 50,
        soilType: SoilType.CLAY,
        phSoil: 6.5,
        temperature: 28,
        humidity: 65,
        windExposure: 50,
        latitude: 10.0452,
        longitude: 105.7469,
        altitude: 15,
      },
      {
        name: 'Trong phòng khách',
        description: 'Ánh sáng gián tiếp qua cửa kính',
        sunlight: Sunlight.PARTIAL_SUN,
        lightDuration: 4,
        lightType: LightType.LED,
        soilMoisture: 30,
        soilType: SoilType.SANDY,
        phSoil: 7.0,
        temperature: 27,
        humidity: 70,
        windExposure: 10,
        latitude: 10.0452,
        longitude: 105.7469,
        altitude: 10,
      },
      {
        name: 'Vườn sau nhà',
        description: 'Khu đất rộng với ánh sáng đầy đủ cả ngày',
        sunlight: Sunlight.FULL_SUN,
        lightDuration: 8,
        lightType: LightType.NATURAL,
        soilMoisture: 60,
        soilType: SoilType.LOAMY,
        phSoil: 6.8,
        temperature: 30,
        humidity: 60,
        windExposure: 40,
        latitude: 10.046,
        longitude: 105.747,
        altitude: 12,
      },
      {
        name: 'Ban công hướng Bắc',
        description: 'Ít nắng, chủ yếu ánh sáng khuếch tán',
        sunlight: Sunlight.SHADE,
        lightDuration: 3,
        lightType: LightType.NATURAL,
        soilMoisture: 45,
        soilType: SoilType.SILTY,
        phSoil: 6.7,
        temperature: 26,
        humidity: 75,
        windExposure: 20,
        latitude: 10.047,
        longitude: 105.745,
        altitude: 18,
      },
      {
        name: 'Trên sân thượng',
        description: 'Nắng gắt cả ngày, gió nhiều',
        sunlight: Sunlight.FULL_SUN,
        lightDuration: 9,
        lightType: LightType.NATURAL,
        soilMoisture: 40,
        soilType: SoilType.CHALKY,
        phSoil: 7.5,
        temperature: 33,
        humidity: 55,
        windExposure: 80,
        latitude: 10.048,
        longitude: 105.744,
        altitude: 25,
      },
      {
        name: 'Gần cửa sổ phòng ngủ',
        description: 'Ánh sáng buổi sáng, dễ chịu cho cây trong nhà',
        sunlight: Sunlight.PARTIAL_SUN,
        lightDuration: 5,
        lightType: LightType.NATURAL,
        soilMoisture: 35,
        soilType: SoilType.PEATY,
        phSoil: 6.2,
        temperature: 27,
        humidity: 65,
        windExposure: 15,
        latitude: 10.049,
        longitude: 105.743,
        altitude: 8,
      },
      {
        name: 'Trong nhà bếp',
        description: 'Ánh sáng nhân tạo từ đèn huỳnh quang',
        sunlight: Sunlight.UNKNOWN,
        lightDuration: 8,
        lightType: LightType.FLUORESCENT,
        soilMoisture: 40,
        soilType: SoilType.SANDY,
        phSoil: 6.9,
        temperature: 29,
        humidity: 70,
        windExposure: 5,
        latitude: 10.05,
        longitude: 105.742,
        altitude: 9,
      },
      {
        name: 'Sân trước',
        description: 'Nắng buổi sáng, bóng râm buổi chiều',
        sunlight: Sunlight.PARTIAL_SUN,
        lightDuration: 6,
        lightType: LightType.NATURAL,
        soilMoisture: 55,
        soilType: SoilType.LOAMY,
        phSoil: 6.6,
        temperature: 28,
        humidity: 68,
        windExposure: 35,
        latitude: 10.051,
        longitude: 105.741,
        altitude: 11,
      },
      {
        name: 'Trong văn phòng',
        description: 'Ánh sáng đèn LED suốt ngày',
        sunlight: Sunlight.UNKNOWN,
        lightDuration: 10,
        lightType: LightType.LED,
        soilMoisture: 30,
        soilType: SoilType.SILTY,
        phSoil: 7.2,
        temperature: 25,
        humidity: 60,
        windExposure: 0,
        latitude: 10.052,
        longitude: 105.74,
        altitude: 7,
      },
      {
        name: 'Nhà kính mini',
        description: 'Kiểm soát nhiệt độ và độ ẩm tốt',
        sunlight: Sunlight.FULL_SUN,
        lightDuration: 7,
        lightType: LightType.NATURAL,
        soilMoisture: 65,
        soilType: SoilType.LOAMY,
        phSoil: 6.4,
        temperature: 29,
        humidity: 80,
        windExposure: 10,
        latitude: 10.053,
        longitude: 105.739,
        altitude: 14,
      },
      {
        name: 'Dưới tán cây lớn',
        description: 'Râm mát, chỉ có ánh sáng lọc qua lá',
        sunlight: Sunlight.SHADE,
        lightDuration: 2,
        lightType: LightType.NATURAL,
        soilMoisture: 70,
        soilType: SoilType.PEATY,
        phSoil: 6.0,
        temperature: 26,
        humidity: 85,
        windExposure: 15,
        latitude: 10.054,
        longitude: 105.738,
        altitude: 13,
      },
      {
        name: 'Bên cửa sổ hướng Đông',
        description: 'Nắng dịu buổi sáng, thích hợp cây cảnh nhỏ',
        sunlight: Sunlight.PARTIAL_SUN,
        lightDuration: 4,
        lightType: LightType.NATURAL,
        soilMoisture: 40,
        soilType: SoilType.SILTY,
        phSoil: 6.5,
        temperature: 27,
        humidity: 70,
        windExposure: 10,
        latitude: 10.055,
        longitude: 105.737,
        altitude: 9,
      },
    ];

    for (const site of defaultSites) {
      const exists = await this.repository.findOne({
        where: { name: site.name },
      });
      if (!exists) {
        await this.repository.save(this.repository.create(site));
      }
    }
  }
}
