import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { SpeciesEntity } from '../../../../species/infrastructure/persistence/relational/entities/species.entity';
import {
  DifficultyLevelEnum,
  SunlightNeedEnum,
} from '../../../../species/species.enum';
import { WaterEnum } from '../../../../waters/waters.enum';
import {
  FertilizerMethodEnum,
  FertilizerTypeEnum,
} from '../../../../fertilizers/fertilizers.enum';

@Injectable()
export class SpeciesSeedService {
  constructor(
    @InjectRepository(SpeciesEntity)
    private repository: Repository<SpeciesEntity>,
  ) {}

  async run() {
    const defaultSpecies: Partial<SpeciesEntity>[] = [
      {
        name: 'Cây Lưỡi Hổ',
        scientificName: 'Sansevieria trifasciata',
        wateringFrequency: 7,
        wateringAmount: 200,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 30,
        fertilizingAmount: 50,
        fertilizingMethod: FertilizerMethodEnum.SOIL_MIXING,
        fertilizerType: FertilizerTypeEnum.ORGANIC,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Trầu Bà',
        scientificName: 'Epipremnum aureum',
        wateringFrequency: 5,
        wateringAmount: 150,
        wateringMethod: WaterEnum.SPRAY,
        fertilizingFrequency: 20,
        fertilizingAmount: 40,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.NPK,
        sunlightNeed: SunlightNeedEnum.SHADE,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Xương Rồng',
        scientificName: 'Cactaceae spp.',
        wateringFrequency: 14,
        wateringAmount: 100,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 60,
        fertilizingAmount: 30,
        fertilizingMethod: FertilizerMethodEnum.SURFACE_SPREAD,
        fertilizerType: FertilizerTypeEnum.INORGANIC,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Sen Đá',
        scientificName: 'Echeveria spp.',
        wateringFrequency: 10,
        wateringAmount: 120,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 45,
        fertilizingAmount: 30,
        fertilizingMethod: FertilizerMethodEnum.SURFACE_SPREAD,
        fertilizerType: FertilizerTypeEnum.INORGANIC,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Kim Ngân',
        scientificName: 'Pachira aquatica',
        wateringFrequency: 6,
        wateringAmount: 250,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 25,
        fertilizingAmount: 60,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.NPK,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Cau Cảnh',
        scientificName: 'Areca catechu',
        wateringFrequency: 5,
        wateringAmount: 300,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 30,
        fertilizingAmount: 70,
        fertilizingMethod: FertilizerMethodEnum.SOIL_MIXING,
        fertilizerType: FertilizerTypeEnum.ORGANIC,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Phát Tài',
        scientificName: 'Dracaena fragrans',
        wateringFrequency: 6,
        wateringAmount: 200,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 20,
        fertilizingAmount: 50,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.NPK,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Lan Ý',
        scientificName: 'Spathiphyllum wallisii',
        wateringFrequency: 4,
        wateringAmount: 180,
        wateringMethod: WaterEnum.SPRAY,
        fertilizingFrequency: 25,
        fertilizingAmount: 40,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.LIQUID,
        sunlightNeed: SunlightNeedEnum.SHADE,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Ngọc Ngân',
        scientificName: 'Aglaonema spp.',
        wateringFrequency: 5,
        wateringAmount: 160,
        wateringMethod: WaterEnum.SPRAY,
        fertilizingFrequency: 30,
        fertilizingAmount: 40,
        fertilizingMethod: FertilizerMethodEnum.FOLIAR_FEED,
        fertilizerType: FertilizerTypeEnum.MICRO_NUTRIENT,
        sunlightNeed: SunlightNeedEnum.SHADE,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Trúc Nhật',
        scientificName: 'Dracaena surculosa',
        wateringFrequency: 6,
        wateringAmount: 180,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 30,
        fertilizingAmount: 45,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.ORGANIC,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Hồng Môn',
        scientificName: 'Anthurium andraeanum',
        wateringFrequency: 5,
        wateringAmount: 150,
        wateringMethod: WaterEnum.SPRAY,
        fertilizingFrequency: 20,
        fertilizingAmount: 40,
        fertilizingMethod: FertilizerMethodEnum.FOLIAR_FEED,
        fertilizerType: FertilizerTypeEnum.LIQUID,
        sunlightNeed: SunlightNeedEnum.SHADE,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Lộc Vừng',
        scientificName: 'Barringtonia acutangula',
        wateringFrequency: 4,
        wateringAmount: 350,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 40,
        fertilizingAmount: 100,
        fertilizingMethod: FertilizerMethodEnum.SOIL_MIXING,
        fertilizerType: FertilizerTypeEnum.MANURE,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.HARD,
      },
      {
        name: 'Cây Dương Xỉ',
        scientificName: 'Nephrolepis exaltata',
        wateringFrequency: 3,
        wateringAmount: 200,
        wateringMethod: WaterEnum.SPRAY,
        fertilizingFrequency: 20,
        fertilizingAmount: 35,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.ORGANIC,
        sunlightNeed: SunlightNeedEnum.SHADE,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Xô Thơm',
        scientificName: 'Salvia officinalis',
        wateringFrequency: 5,
        wateringAmount: 150,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 25,
        fertilizingAmount: 40,
        fertilizingMethod: FertilizerMethodEnum.SOIL_MIXING,
        fertilizerType: FertilizerTypeEnum.COMPOST,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Húng Quế',
        scientificName: 'Ocimum basilicum',
        wateringFrequency: 3,
        wateringAmount: 120,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 15,
        fertilizingAmount: 30,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.NPK,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Rau Má',
        scientificName: 'Centella asiatica',
        wateringFrequency: 2,
        wateringAmount: 250,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 20,
        fertilizingAmount: 30,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.ORGANIC,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Lô Hội',
        scientificName: 'Aloe vera',
        wateringFrequency: 12,
        wateringAmount: 150,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 50,
        fertilizingAmount: 30,
        fertilizingMethod: FertilizerMethodEnum.SURFACE_SPREAD,
        fertilizerType: FertilizerTypeEnum.INORGANIC,
        sunlightNeed: SunlightNeedEnum.FULL_SUN,
        difficultyLevel: DifficultyLevelEnum.EASY,
      },
      {
        name: 'Cây Trúc Mây',
        scientificName: 'Rhapis excelsa',
        wateringFrequency: 5,
        wateringAmount: 200,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 30,
        fertilizingAmount: 50,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.COMPOST,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.MODERATE,
      },
      {
        name: 'Cây Bàng Singapore',
        scientificName: 'Ficus lyrata',
        wateringFrequency: 6,
        wateringAmount: 250,
        wateringMethod: WaterEnum.ROOT,
        fertilizingFrequency: 25,
        fertilizingAmount: 60,
        fertilizingMethod: FertilizerMethodEnum.LIQUID_FEED,
        fertilizerType: FertilizerTypeEnum.NPK,
        sunlightNeed: SunlightNeedEnum.PARTIAL_SUN,
        difficultyLevel: DifficultyLevelEnum.HARD,
      },
    ];

    for (const species of defaultSpecies) {
      const exists = await this.repository.findOne({
        where: { scientificName: species.scientificName },
      });
      if (!exists) {
        await this.repository.save(this.repository.create(species));
      }
    }
  }
}
